permalink: /:categories/:title
url: userbound.com
sass:
    style: compressed

navigation_a:
  - text: Front End
    href: /front-end
  - text: Interfaces
    href: /interfaces

navigation_b:
  - text: '&#9993'
    href: /art
