permalink: blog/:title
url: userbound.com
sass:
    style: compressed

navigation_a:
  - text: Interfaces
    href: /interfaces
  - text: Front End
    href: /front-end

navigation_b:
  - text: '&omega;'
    href: /misc
  - text: '&beta;'
    href: /blog
  - text: '&#9993'
    href: /about
