permalink: /:categories/:title
url: userbound.com
sass:
    style: compressed

navigation:
  - text: Front End
    href: /front-end
  - text: Interfaces
    href: /interfaces
  - text: '&#9993'
    href: /art
