permalink: blog/:title
url: userbound.com
sass:
    style: compressed

navigation_a:
  - text: Front End
    href: /front-end
    slug: front-end
  - text: Interface
    href: /interfaces
    slug: interfaces

navigation_b:
  - text: '&omega;'
    href: /miscart
    slug: art
  - text: '&beta;'
    href: /blog
    slug: blog
  - text: '&#9993'
    href: /contact
    slug: contact

